In [ ]:
import numpy as np
import pandas as pd

# a. Extraer la información del archivo y crear el DataFrame.

In [ ]:
file_path = '/content/country_vaccinations.csv'
df = pd.read_csv(file_path)

# b. Mostrar la estructura y tipos de datos de cada columna para identificar qué operaciones puedes realizar con cada una de ellas, asegurándote que las columnas con fechas sean del tipo datetime64.

In [ ]:
df.dtypes

df['date'] = pd.to_datetime(df['date'])
df.dtypes

country                                        object
iso_code                                       object
date                                   datetime64[ns]
total_vaccinations                            float64
people_vaccinated                             float64
people_fully_vaccinated                       float64
daily_vaccinations_raw                        float64
daily_vaccinations                            float64
total_vaccinations_per_hundred                float64
people_vaccinated_per_hundred                 float64
people_fully_vaccinated_per_hundred           float64
daily_vaccinations_per_million                float64
vaccines                                       object
source_name                                    object
source_website                                 object
dtype: object

# c. Determinar la cantidad de vacunas aplicadas de cada compañía (con base en cómo lo reporta cada país en la columna vaccines, en otras palabras, agrupe por vaccines y realice la sumatoria).

In [ ]:
df.groupby('vaccines')['daily_vaccinations'].sum()

vaccines
Abdala, Johnson&Johnson, Oxford/AstraZeneca, Pfizer/BioNTech, Soberana02, Sputnik Light, Sputnik V                              9616160.0
Abdala, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sputnik V                                            201816053.0
Abdala, Sinopharm/Beijing, Sinovac, Soberana02, Sputnik Light, Sputnik V                                                       37861146.0
Abdala, Soberana Plus, Soberana02                                                                                              33802957.0
COVIran Barekat, Covaxin, FAKHRAVAC, Oxford/AstraZeneca, Razi Cov Pars, Sinopharm/Beijing, Soberana02, SpikoGen, Sputnik V    146357015.0
                                                                                                                                 ...
Pfizer/BioNTech, Sinovac, Turkovac                                                                                            147484328.0
Pfizer/BioNTech, Sputnik V                                                                                                        68643.0
QazVac, Sinopharm/Beijing, Sputnik V                                                                                           20891256.0
Sinopharm/Beijing                                                                                                                893824.0
Sinopharm/Beijing, Sputnik V                                                                                                   14398697.0
Name: daily_vaccinations, Length: 84, dtype: float64

# d. Obtener la cantidad de vacunas aplicadas en todo el mundo.

In [ ]:
print(df['daily_vaccinations'].sum())

11320239871.0

# e. Calcular el promedio de vacunas aplicadas por país.

In [ ]:
df.groupby('country')['daily_vaccinations'].mean()

country
Afghanistan          14610.681934
Albania               6276.210046
Algeria              33904.356436
Andorra                367.716019
Angola               44821.457584
                         ...
Wales                15518.411765
Wallis and Futuna       33.886486
Yemen                 2556.115756
Zambia                9649.805158
Zimbabwe             21669.066832
Name: daily_vaccinations, Length: 223, dtype: float64

# f. Determinar la cantidad de vacunas aplicadas el día 29/01/21 en todo el mundo.

In [ ]:
print(df[df['date'] == '2021-01-29']['daily_vaccinations'].sum())

4884052.0

# g. Crear un dataframe nuevo denominado conDiferencias que contenga los datos originales y una columna derivada (diferencias) con las diferencias de aplicación entre las columnas daily_vaccionations y daily_vaccionations_raw.

In [ ]:
conDiferencias = df.copy()
conDiferencias['diferencias'] = conDiferencias['daily_vaccinations'] - conDiferencias['daily_vaccinations_raw']
conDiferencias.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website,diferencias
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,NaN
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,NaN
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,NaN
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,NaN
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,NaN

# h. Obtener el periodo de tiempo entre el registro con fecha más reciente y el registro con fecha más antigua.

In [ ]:
print(conDiferencias['date'].max() - conDiferencias['date'].min())

482 days 00:00:00

# i. Crear un dataframe nuevo denominado conCantidad que contenga los datos originales y una columna derivada (canVac) con la cantidad de vacunas utilizadas cada día (usar la columna vaccines y separar por el carácter , ).

In [ ]:
conCantidad = df.copy()
conCantidad['canVac'] = conCantidad['vaccines'].str.split(',').str.len()
conCantidad.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website,canVac
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,4
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,4
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,4
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,4
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,4

# j. Generar un dataframe denominado antes20 con todos los registros que se hayan realizado antes del 20 de diciembre de 2020.

In [ ]:
antes20 = df[df['date'] < '2020-12-20']
antes20.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
13403,Canada,CAN,2020-12-14,5.0,5.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,"Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...",Official data from provinces via covid19tracke...,https://covid19tracker.ca/vaccinationtracker.html
13404,Canada,CAN,2020-12-15,727.0,727.0,NaN,722.0,722.0,0.00,0.00,NaN,19.0,"Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...",Official data from provinces via covid19tracke...,https://covid19tracker.ca/vaccinationtracker.html
13405,Canada,CAN,2020-12-16,3025.0,3025.0,NaN,2298.0,1510.0,0.01,0.01,NaN,40.0,"Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...",Official data from provinces via covid19tracke...,https://covid19tracker.ca/vaccinationtracker.html
13406,Canada,CAN,2020-12-17,7279.0,7279.0,NaN,4254.0,2425.0,0.02,0.02,NaN,64.0,"Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...",Official data from provinces via covid19tracke...,https://covid19tracker.ca/vaccinationtracker.html
13407,Canada,CAN,2020-12-18,11296.0,11296.0,NaN,4017.0,2823.0,0.03,0.03,NaN,74.0,"Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...",Official data from provinces via covid19tracke...,https://covid19tracker.ca/vaccinationtracker.html

# k. Obtener un dataframe denominado pfizer con todos los registros donde se haya utilizado la vacuna Pfizer.

In [ ]:
pfizer = df[df['vaccines'].str.contains('Pfizer')]
pfizer.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/

# l. Almacenar los dataframes generados (conDiferencias, conCantidad, antes20 y pfizer) en un archivo de Excel denominado resultadosReto.xlsx, donde cada dataframe ocupe una hoja diferente. Se recomienda ver la documentación de pd.ExcelWriter.

In [ ]:
!pip install xlsxwriter
from xlsxwriter import Workbook

Collecting xlsxwriter
  Downloading xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Downloading xlsxwriter-3.2.9-py3-none-any.whl (175 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 5.4 MB/s eta 0:00:00
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.9

In [ ]:
writer = pd.ExcelWriter('resultadosReto.xlsx', engine='xlsxwriter')

conDiferencias.to_excel(writer, sheet_name='conDiferencias', index=False)
conCantidad.to_excel(writer, sheet_name='conCantidad', index=False)
antes20.to_excel(writer, sheet_name='antes20', index=False)
pfizer.to_excel(writer, sheet_name='pfizer', index=False)

writer.close()

/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://ais.paho.org/imm/IM_DosisAdmin-Vacunacion.asp' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://web.facebook.com/SVGHEALTH/posts/437021804887233' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://stats.pacificdata.org/vis?tm=covid&pg=0&df[ds]=SPC2&df[id]=DF_COVID_VACCINATION&df[ag]=SPC&df[vs]=1.0' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://covid19.who.int/' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://africacdc.org/covid-19-vaccination/' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://coronavirus.data.gov.uk/details/vaccinations' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://vakcinacija.gov.rs/' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://data.gov.sg/dataset/covid-19-vaccination' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://github.com/Institut-Zdravotnych-Analyz/covid19-data/raw/main/Vaccination/OpenData_Slovakia_Vaccination_AgeGroup_District.csv' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://covid-19.sledilnik.org/sl/stats' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://sacoronavirus.co.za/latest-vaccine-statistics/' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://ncv.kdca.go.kr/' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov/documentos/Informe_Comunicacion_20220325.ods' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://www.epid.gov.lk/web/images/pdf/corona_vaccination/covid_vaccination_2022-03_22.pdf' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://laatjevaccineren.sr/' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://fohm.se/smittskydd-beredskap/utbrott/aktuella-utbrott/covid-19/statistik-och-analyser/statistik-over-registrerade-vaccinationer-covid-19/' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://opendata.swiss/en/dataset/covid-19-schweiz?detGeo=CH' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://www.cdc.gov.tw/Category/Page/9jFXNbCe-sFK9EImRRi2Og' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://ddc.moph.go.th/covid19-dashboard/' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://services3.arcgis.com/x3I4DqUw3b3MfTwQ/arcgis/rest/services/service_7a519502598f492a9094fd0ad503cf80/FeatureServer/0/query' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://web.facebook.com/santetunisie.rns.tn/posts/339797681524034?__cft__[0]=AZUiZe_DZCgQaUfW53dSTtXxKD5Vmq3M4OkNzKUMnMjzyKYqwPgH6EV-do3PCuT4TqokRZFYjLLshZ87APo1I0dbZHgTHn-95N8CB7Crpo5q1AShf3f9AQYWATKZCptNluocUhFJ8tKk3Z4cIg3qRVhQ&__tn__=%2CO%2CP-R' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://covid19asi.saglik.gov.tr/' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://health-security.rnbo.gov.ua' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://fcsc.gov.ae/en-us/Pages/Covid19/UAE-Covid-19-Updates.aspx' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://data.cdc.gov/Vaccinations/COVID-19-Vaccination-Trends-in-the-United-States-N/rh2h-3yt2' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://monitor.uruguaysevacuna.gub.uy/' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://covid19.gov.vn/ngay-23-3-so-mac-moi-covid-19-giam-con-127883-ca-tuyen-quang-bo-sung-gan-13000-f0-171220323181603013.htm' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://rtc-planning.maps.arcgis.com/apps/dashboards/3b3a01c1d8444932ba075fb44b119b63' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(
/usr/local/lib/python3.12/dist-packages/xlsxwriter/worksheet.py:1321: UserWarning: Ignoring URL 'https://www.arcgis.com/home/webmap/viewer.html?url=https://services9.arcgis.com/DnERH4rcjw7NU6lv/ArcGIS/rest/services/Vaccine_Distribution_Program/FeatureServer&source=sd' since it exceeds Excel's limit of 65,530 URLs per worksheet.
  warn(